fix: deactivate the csvts NCNN test when caffe is not built
jolibrain/deepdetect pull request #1136
Opened 2021-01-15 19:38 UTC by beniz

2021-01-18 08:13 UTC, fantes requested changes

2021-01-18 08:13 UTC, fantes commented on tests/ut-ncnnapi.cc
> +      = "{\"mllib\":\"ncnn\",\"description\":\"my ts "
the idea here was to learn and predict with caffe, then to compare to ncnn prediction, here you try to learn with ncnn ?

2021-01-18 08:13 UTC, fantes commented on tests/ut-ncnnapi.cc
> +          "\"caffe\",\"scale\":true,\"min_vals\":"
this makes me core dump : "connector":"caffe" ?

2021-01-18 08:50 UTC, beniz commented
Thank you, these are typos, I went too fast.

2021-01-18 09:02 UTC, fantes approved these changes

2021-01-19 14:09 UTC, BynaryCobweb approved these changes

2021-01-21 13:24 UTC, sileht commented
@mergifyio update

2021-01-21 17:13 UTC, merged