fix: -Werror=deprecated-copy gcc 9.3
jolibrain/deepdetect pull request #1156
Opened 2021-01-27 09:32 UTC by sileht

This just uses default APIData constructors instead of have to defined
all copy/move semantics.

Instead of using the special constructor for RapidJson, we just call the
fromRapidJson() method when needed.

2021-01-27 11:22 UTC, fantes approved these changes

2021-01-27 21:10 UTC, beniz approved these changes

2021-01-28 12:08 UTC, sileht commented
@mergifyio update

2021-01-28 17:04 UTC, sileht commented
@Mergifyio rebase

2021-01-29 18:16 UTC, sileht commented
@Mergifyio rebase

2021-02-01 20:06 UTC, fantes commented
@Mergifyio rebase

2021-02-02 12:25 UTC, fantes requested changes

2021-02-02 12:25 UTC, fantes commented on tests/ut-conn.cc
> +  ad.fromRapidJson(d);
typo here ap/ad

2021-02-03 11:20 UTC, merged