build: allow to disable swagger
jolibrain/deepdetect pull request #1445
Opened 2022-06-10 13:39 UTC by Bycob

2022-06-10 13:56 UTC, fantes approved these changes

2022-06-10 14:44 UTC, fantes requested changes

2022-06-10 14:44 UTC, fantes commented on src/CMakeLists.txt
> +      add_dependencies(oatpp-swagger)
add_dependencies(oatpp-swagger) -> add_dependencies(ddetect oatpp-swagger)

2022-06-10 14:50 UTC, Bycob commented on src/CMakeLists.txt
> +      add_dependencies(oatpp-swagger)
https://media.giphy.com/media/zNbiX43QsqUAU/giphy.gif

2022-06-10 14:55 UTC, Bycob commented on src/CMakeLists.txt
> +      add_dependencies(oatpp-swagger)
! [image](https://media.giphy.com/media/zNbiX43QsqUAU/giphy.gif)

2022-06-14 11:48 UTC, fantes approved these changes

2022-06-14 12:01 UTC, beniz approved these changes

2022-06-14 12:02 UTC, merged